wikitree/wikitree-browser-extension

webpack/webpack.common.js

The line being deleted requires an additional NODE_ENV environment variable which is not provided anywhere.
Without this line `npm run build-dev` and `npm run watch` build a non-minimized package with source maps and `npm run build` builds a minimized package.
Minimization decreases the content JS (content.js and vendor.js) file size from 718kB to 324kB.

Make the production build minimized

---

src/content.js
src/core/features.js
src/features/familyTimeline/familyTimeline.js
src/features/features.js
src/features/printerfriendly/printerfriendly.js
src/options.js

When adding a new feature:
- `src/options.js` file no longer needs to be modified
- feature's `name`, `id`, `description` and `category` are now defined in the feature source file, i.e. together with the feature
- feature code no longer has to call `chrome.storage.sync`
This PR is a suggestion with changes to `familyTimeline` and `printerFriendly` as examples. If everyone is OK with this change, I'll update other features and the documentation.

Change the way features are registered

---

src/content.js
src/features/categoryFinderPins/categoryFinderPins.js
src/options.js

On the locations dropdown, there are map pins.  This looks the same, but the pins go to category pages.

Add pins to Category Finder, linking to category pages

---

src/features/features.js

It was accidentally removed in #69

Add import for categoryFinderPins

---

src/core/features.js
src/features/features.js
src/features/sortBadges/sortBadges.css
src/features/sortBadges/sortBadges.js
src/options.js

This is to hide or move the club badges down (which probably do the same job).  I think this is working OK, but please take a look.  It puts two links on the member's profile page (below the badges) and two buttons on the badges page.  The links on the profile page go to the badges page, click the buttons to run the functions, and then return the user to the profile page.  Let me know if you see anything strange.
I've added this as 'Other' on the options page.

Sort badges

---

.babelrc
jest.config.js
package-lock.json
package.json
src/features/agc/agc.test.js
src/features/agc/agc_content.js
src/features/agc/library/editbio.js
src/testing/styleMock.js

Remember to run `npm install` before running tests because new dependencies need to be installed.
Running tests: `npm test`
Other useful commands:
Run tests on each file save: `npm test -- --watch`
Run tests with more verbose output: `npm test -- --verbose`
To add tests to other features or core files, add files that end with `.test.js`.
More details about testing with jest: https://jestjs.io/
Sample output:

Convert AGC tests to use jest testing library

---

jest.config.js
package.json
src/content.js
src/core/options/options_registry.js
src/core/options/options_storage.js
src/features/agc/agc.test.js
src/features/agc/agc_content.js
src/features/agc/agc_options.js
src/features/register_feature_options.js
src/options.js

This change simplifies the project configuration and makes it more consistent.
@RobPavey introduced these changes alongside a larger change #90. We agreed to merge Rob's PR quicker and leave this file renaming for a subsequent PR.

Rename mjs files to js

---

src/features/genderPredictor/genderPredictor.js
src/features/genderPredictor/gender_predictor_options.js

After I merged Ian's PR I synced it and tested it. I noticed that it was testing for darkMode being enabled rather than featurePredictor. So I fixed that.
As part of that change I made the feature ID more consistent with the other ones.

Fix incorrect feature id in test (was "darkMode" should be "genderPredictor")

---

docs/contributing.md
src/core/editToolbar.js
src/core/options/options_registry.js
src/core/options/options_storage.js
src/features/agc/agc_options.js
src/features/darkMode/darkMode_options.js
src/features/genderPredictor/gender_predictor_options.js
src/features/redir_ext_links/redir_ext_links_options.js
src/features/register_feature_options.js
src/options.js

When a feature is registered it specifies a defaultValue which says whether it is enabled by default or not.
The options page takes those default values into account. So does `checkIfFeatureEnabled`.
As part of this change I switched `editToolbar.js` to use `options_storage` to check whether features are enabled. All other features are already doing that now.
I may not have correctly set the desired values for which features should be enabled by default but these are easily changed.
This completes the work for these two issues: https://github.com/wikitree/wikitree-browser-extension/issues/49 and https://github.com/wikitree/wikitree-browser-extension/issues/103

Implement a default enabled state for features

---

src/features/agc/agc_content.js

We want the button on  the left but current implementation is dodgy - only puts it on the left if the content script does it before the web page does.

Fix timing bug in agc that cause button to be on right of toolbar

---

src/content.js
src/features/categoryDisplay/categoryDisplay.js
src/features/register_feature_options.js

[Requested in G2G](https://www.wikitree.com/g2g/1490020/have-you-seen-the-wikitree-browser-extension?show=1490664#a1490664); from the old WikiTree Toolkit extension.
When enabled, this will move the category links to the top of profiles.

Add categoryDisplay feature

---

src/manifest/manifest-firefox.json

Solution found here: https://stackoverflow.com/questions/66853081/firefox-error-networkerror-when-attempting-to-fetch-resource-only-from-extensio

Add permissions to use WikiTree API in Firefox manifest

---

src/content.js
src/features/distanceAndRelationship/distanceAndRelationship.js
src/features/familyTimeline/familyTimeline.js
src/features/register_feature_options.js
src/features/sort_theme_people/sort_theme_people.css
src/features/sort_theme_people/sort_theme_people.js
src/manifest/manifest-firefox.json

This is for the connection finder theme people at the bottom of profiles.  It gets a theme title from either the home page or my server.  Then it adds a 'Theme List' button.  Clicking this sorts the people into a table ordered by degree from the profile person.  It also gets the Relationship Finder results for the profile person and the featured people and puts any positive results in the table.
I'd appreciate any input on this - things like the name or design.

Sort theme people

---

src/content.js
src/features/collapsible_sources/collapsible_sources.css
src/features/collapsible_sources/collapsible_sources.js
src/features/register_feature_options.js

To make a profile page shorter, this collapses inline citations onload.  To see the inline citations, click the ▶ button next to the Sources heading, click the superscript number of the citation, or use the Source Preview feature of this extension.

Collapsible Sources

---

src/manifest/manifest-firefox.json

The WT+ part of the extension needs this.

Add WT+ To Firefox Manifest

---

src/content.js
src/features/register_feature_options.js
src/features/sticky_toolbar/sticky_toolbar.css
src/features/sticky_toolbar/sticky_toolbar.js

Makes the toolbar on the editor on edit pages stick to the top of the screen and not scroll out of sight.

StickyToolbar

---

src/features/clipboard_and_notes/clipboard_and_notes.js
src/features/extra_watchlist/extra_watchlist.js

Moved the CSS import back to the top level as its late loading caused the buttons to kind of flash as they take the rules of the WT buttons before the CSS to modify them.

Stop flashing

---

src/features/g2g/g2g.css
src/features/g2g/g2g.js
src/features/g2g/g2g_.css
src/features/sticky_toolbar/sticky_toolbar.css
src/features/sticky_toolbar/sticky_toolbar.js

Avoid some flashing. 
+ Re-direct entries without numbers in the WTID Go box to the 'genealogy' page.

Fix G2G style and Sticky Toolbar

---

package-lock.json
src/content.js
src/features/dna_table/dna_table.js
src/features/register_feature_options.js
src/features/suggested_matches_filters/suggested_matches_filters.css
src/features/suggested_matches_filters/suggested_matches_filters.js

Adds filter buttons to the suggested matches table on the new profile creation page.
Location 1 (Click 'Location' once): Checks location words of new person and their family members against the locations of each suggested match. Also moves better matches to the top of the list.
Location 2 (Click 'Location' again): The same as location 1, but ignores the country.
Name 1 (Click 'Name' once): Filters on the middle name.
Name 2 (Click 'Name' again): Matches only exact names.
Date 1: Narrows the list down to people born up to two years before or after the new person.
Date 2: One year before or after the new person.
Date 3: The same year as the new person.

Suggested matches filter

---

src/features/distanceAndRelationship/distanceAndRelationship.js

The wordig "Your common ancestor, XYZ, is <his/her/their> <relation>" is changed to "Your <relation> YXZ, is <his/her/their> <relation>", e.g "Your 6th great-grandfather, Johannes Franke (1686-1743), is his 2nd great-grandfather"

Improve wording in relationship feature

---

src/content.js
src/core/profileClasses.js
src/core/toggleCheckbox.css
src/features/accessibility/accessibility.css
src/features/accessibility/accessibility.js
src/features/accessibility/accessibility_options.js
src/features/debugProfileClasses/debugProfileClasses.css
src/features/debugProfileClasses/debugProfileClasses.js
src/features/readingMode/readingMode.css
src/features/readingMode/readingMode.js
src/features/readingMode/readingMode_options.js
src/features/register_feature_options.js

This started out as an enhancement to alter the spacing of sources for people with vision problems, based on comments from a [G2G post](https://www.wikitree.com/g2g/1543388/preferred-formatting-of-references-and-sources).
As I got into identifying where all of the sources could be and how the lists were formatted, I realized that there was not really a good way to identify sections of a profile/biography simply based on IDs or classes in the HTML. I noticed [issue #125](https://github.com/wikitree/wikitree-browser-extension/issues/125) about creating a "reading mode" and started down that path, following the recommended design and adding some extra features of my own.
Because both of these features use the same logic, there are two files that I put in "core" so that can be shared:
- …

New features: Accessibility Options and Reading Mode

---

src/features/readability/readability.js
src/features/readability/readability_options.js

Fixed issues found on Crabtree-3037:
- adjacent citations separated by only whitespace were not combined, so comma separators were missing
- leading asterisks in <ref> tags interfered with options to remove labels or to add bold at the beginning of sources
thanks Ian!

Readability bug fixes

---

src/core/profileClasses.js
src/features/debugProfileClasses/debugProfileClasses.css
src/features/readability/readability.css
src/features/readability/readability.js
src/features/readability/readability_options.js

- updated profileClasses to distinguish between standalone images and tables with images inside
- fixed issue with Reagan-1 and whitespace before "See Also:" preventing it from being detected as part of the sources section
- enable any link referring to an ID or anchor in the sources section automatically expand them (not only for citations)
- minor handling of whitespace and asterisks before bold source labels (Crabtree-3037)
- updated link and a few defaults on the feature options

tweaks to Readability Options based on a few problematic profiles

---

src/core/profileClasses.js
src/features/debugProfileClasses/debugProfileClasses.css
src/features/readability/readability.css
src/features/readability/readability.js
src/features/readability/readability_options.js

The thumbnail image and DNA connections have special options for when to hide them. Since they are always shown on the page whether a user has uploaded an image or connected any DNA kits, special options were added to handle those cases only.
- never
- in reading mode
- **in reading mode when empty** (or default)
- **always when empty** (or default)
- always

enhanced options for thumbnail image and DNA connections

---

src/core/profileClasses.js
src/features/readability/readability.js

It should only skip when the user has "always" hide selected. It was previously also skipping if the user had selected to "never" hide citations.

bug fix for citations in Readability Options

---

src/features/readability/readability.js

- load the page with Sources expanded instead of collapsed if the URL is targeting an anchor in that section
- also replaced jQuery.change with jQuery.on("change")

Readability Options update for links with anchors

---

src/core/profileClasses.js
src/features/readability/readability.js
src/features/readability/readability_options.js

This adds an option for indentation of "See also:" and any other plain-text elements within the sources section.
It has the same effect as prefixing it with a colon (":See also:") in the biography, but this way editors don't have to do custom formatting or indentation, which will hopefully promote more standard formatting across all profiles.

addition to Readability Options for indentation of "See also:"

---

src/features/sticky_header/sticky_header.css

This shrinks the text fields a little bit and also limits the width of the "person" menu item which can vary based on the length of the last name so that the menu won't drop into the page area.
Example: https://www.wikitree.com/wiki/Van_Munster-106
Absurd example to show how it would get cut off: https://www.wikitree.com/genealogy/ABCDEFGHIJKLMNOPQRSTUVWXYZ

prevent Sticky Header overlapping the page

---

public/main.css
public/popup.html
src/features/readability/readability_options.js
src/features/register_feature_options.js
src/options.js
src/popup.js
src/upload.js
webpack/webpack.common.js

(Separate pull request from style changes since this is a major feature change. See #294 first.)
The "Default" button at the top becomes "Settings" and will open up a dialog box. It includes options to enable default features (like the original default button did) and adds options to export/import the entire JSON for the feature options. An additional option allows you to clear the settings and reset everything, including all of the feature options, to the default values as if you had installed the extension from scratch.
If opened from a tab on the WikiTree domain, the options from backup/restore of data from features like My Menu and Extra Watchlist will also show up at the bottom of the dialog box (instead of being placed at the bottom of the feature list).
May need to be tested on …

added and consolidated options for backup/restore of settings and data

---

public/main.css
src/features/readability/readability_options.js
src/features/register_feature_options.js
src/options.js

- set link colors to match WikiTree
- added "link" property to features to automatically show the "More details" link after the description consistently
- aligned creator/contributors (in both singular and plural forms, depending on the list) to the right and removed . at the end
- updated button colors to use hover feedback (gray to green)
- smooth scroll the feature options to the center when "Show options" is clicked
- made the header at the top sticky and added a category bar to quickly scroll to different sections

Updated styles on WBE options page

---

src/features/readability/readability.css
src/features/readability/readability.js
src/features/readability/readability_options.js
src/features/sticky_header/sticky_header.css

- added "only on demand" option for collapsing sources in Readability Options
- exclude elements like toggle buttons and sticky header from printing
- sticky_header.css has few changes other than whitespace from indenting under a media query

Readability Options update
