wikitree/wikitree-browser-extension

features/sourcepreview/sourcepreview.js

Removed profile and space page dependency. Added mutation observer to catch edit page previews.

Fixed Issue #6

---

core/js/options.js
features/distanceAndRelationship/README.md
features/distanceAndRelationship/distanceAndRelationship.css
features/distanceAndRelationship/distanceAndRelationship.js
manifest.json
thirdparty/dexie.js

This adds the distance (degrees) between the user and the profile person and any relationship between the two people.

Added Distance and Relationship feature

---

features/familyTimeline/familyTimeline.js

There was a problem where World War II was  displayed as World War Ii.  The issue was with how the function capitalizefirstletter was being used.
This was in the timeline.

Fixed issue where II is Ii in World War 2

---

core/js/common.js
features/spacepreview/spacepreview.js
manifest.json
thirdparty/jquery.hoverDelay.min.js

Added jquery.hoverDelay and changed spacePreviews to persistent based on #25.
Changed regex matching pattern for profilePage to negate the inclusion of pages using a semicolon in #26.

Problems with space page preview

---

core/js/options.js
core/options.html

Removed the Save button;
Saving all options on click of any one.

Automatically save options

---

features/randomProfile/randomProfile.js

Preparation step before introducing modules

Added const keywords to randomProfile.js

---

features/locationsHelper/locationsHelper.js

Preparation step before introducing modules

Added const and let keywords to locationHelper.js

---

package-lock.json
package.json

Run `npm run zip` to get a fresh `wikitree-browser-extension.zip` file

Add zip script

---

package-lock.json
package.json
src/features/randomProfile/randomProfile.js

The source for the wikitree-js library is at https://github.com/PeWu/wikitree-js
What do you think about moving this repository to the [wikitree](https://github.com/wikitree) GitHub organization?

Use wikitree-js library for WikiTree API calls in randomProfile.js

---

package-lock.json
package.json
src/features/randomProfile/randomProfile.js

Reverts wikitree/wikitree-browser-extension#62
I'm getting errors when building after this (in randomProfile.js).  
I should have checked it properly earlier (sorry), but I think I need to revert this for the moment.

Revert "Use wikitree-js library for WikiTree API calls in randomProfile.js"

---

.github/workflows/test.yml

This will run tests (currently only AGC tests) on each pull request before it is merged. Tests will also be run after a commit is pushed to the repository.
Apart from tests, the action runs `npm run build` that will detect some issues like bad module imports.

Add GitHub Action to run tests for each PR and commit

---

public/background.js

Add update action (open the update page);
Add another install action (open the extension page)

Add update action (open the update space page)

---

src/core/editToolbar.css
src/core/editToolbar.js

#editToolbarButton & #editToolbarDiv >
.editToolbarButton & .editToolbarDiv

Avoid re-using IDs

---

public/main.css
public/options.html
src/options.js

Add a title;
Add the WT logo;
Add the WT header background;
Move the global on/off switch to the right

Redesign the Options page a little

---

package.json

Run `npm run zip-firefox` to get a packaged Firefox extension

Add `zip-firefox` script

---

src/features/distanceAndRelationship/distanceAndRelationship.js
src/features/familyGroup/familyGroup.js
src/features/familyTimeline/familyTimeline.js

Features changed:
- distanceAndRelationship
- familyGroup
- familyTimeline

Use wikitree-js library for API calls in 3 features

---

package-lock.json
src/features/appsMenu/appsMenu.js
src/features/locationsHelper/locationsHelper.js

+ define 'years' in locationsHelper

Remove remote call for apps menu

---

package-lock.json
package.json
src/features/randomProfile/randomProfile.js
src/features/randomProfile/randomProfile.test.js
src/testing/pages/Tolkien-1.html
src/testing/update_test_pages.js

The test is rather simple but I'd like it to serve as an example how you can write DOM tests.
This test doesn't use the browser, so there's no way to check actual visible changes. It checks if the modified "source" of the page is correct (menu item added) and checks if clicking the menu item runs the correct code.
This test uses the Tolkien-1 profile. The profile page is saved as `Tolkien-1.html` in the repository and it is not automatically in sync with the live wikitree.com site. To update a new version of the `Tolkien-1.html` file, run `npm run update-test-pages`. Note that you need to log in with a WikiTree account to update this file because the page looks different for logged in users. In particular, not-logged-in users don't see the "Find" menu.

Add test for randomProfile feature

---

src/content.js
src/features/g2g/g2g.css
src/features/g2g/g2g.js
src/features/g2g/g2g_options.js
src/features/register_feature_options.js

This adds nine features to G2G pages, bundled together as one feature with nine options.

Add various features to G2G

---

src/content.js
src/features/google_search_box/google_search_box.css
src/features/google_search_box/google_search_box.js
src/features/register_feature_options.js

Add Google Search Box to the bottom of every page

Google Search Box

---

src/features/distanceAndRelationship/distanceAndRelationship.js
src/features/familyGroup/familyGroup.js
src/features/familyTimeline/familyTimeline.js

The Distance and Relationship feature was broken by #119.  Changing to checkIfFeatureEnabled removed the Family Timeline button.

Fix bugs introduced by earlier merges

---

src/features/sourcepreview/sourcepreview.js

Added a statement for sourcePreview to only activate when both inline citations and the <references /> tag are available.

Add checking for <references />

---

src/features/clipboard_and_notes/clipboard_and_notes.css
src/features/clipboard_and_notes/clipboard_and_notes.js

Fix this - https://www.wikitree.com/g2g/1490020/have-you-seen-the-wikitree-browser-extension?show=1491516#a1491516 - and this - https://www.wikitree.com/g2g/1490020/have-you-seen-the-wikitree-browser-extension?show=1492086#a1492086 and add clipboard to the marriage edit page.

Fix the Clipboard

---

public/background.js
public/main.css
src/manifest/manifest-chrome.json
src/manifest/manifest-firefox.json

We currently don't have a popup window.  Until we find a need for one, let's use the options page.

Use options.html as the popup

---

package-lock.json
src/features/familyTimeline/familyTimeline.js

Fix this issue: https://www.wikitree.com/g2g/1490020/have-you-seen-the-wikitree-browser-extension?show=1492908#a1492908.

Fix Timeline

---

src/content.js
src/features/edit_family_data/edit_family_data.css
src/features/edit_family_data/edit_family_data.js
src/features/register_feature_options.js

See here: https://www.wikitree.com/wiki/Space:WikiTree_BEE#Birth_and_death_dates_and_locations_on_.27new_profile.27_pages

Birth and death dates and locations on 'new profile' pages

---

src/content.js
src/features/distanceAndRelationship/distanceAndRelationship.js
src/features/register_feature_options.js
src/features/what_links_here/what_links_here.css
src/features/what_links_here/what_links_here.js
src/features/what_links_here/what_links_here_options.js

Adds a 'What Links Here' button to the Find menu. Click to go to the What Links Here page; right-click to copy wiki markdown for links to what links to the page.

What Links Here

---

src/content.js
src/features/format_source_reference_numbers/format_source_reference_numbers.js
src/features/format_source_reference_numbers/format_source_reference_numbers_options.js
src/features/register_feature_options.js

Hide source reference numbers or make them smaller.
This was requested on G2G not long ago.

Format source reference numbers

---

src/content.js
src/features/access_keys/access_keys.js
src/features/register_feature_options.js

Adds access keys. g: G2G Recent Activity; r: Random Profile, n: Nav Home Page; h: Help Search; s: Save; e: Edit; k: Category; p: Preview. (<a href='https://en.wikipedia.org/wiki/Access_key'>More details</a>)

Access keys

---

src/features/clipboard_and_notes/clipboard_and_notes.css
src/features/clipboard_and_notes/clipboard_and_notes.js

Fixed this: https://discord.com/channels/494893309152722955/494893309152722957/1047962298997805056 .

Fix a problem with the clipboard

---

src/features/custom_change_summary_options/custom_change_summary_options.js
src/features/custom_change_summary_options/custom_change_summary_options_options.js

See here: https://www.wikitree.com/wiki/Space:WikiTree_Browser_Extension#comment_6946735 .

Make moving save box optional

---

src/content.js
src/features/dna_table/dna_table.css
src/features/dna_table/dna_table.js
src/features/register_feature_options.js

See here: https://www.wikitree.com/g2g/1501051/name-list-with-birthplace.

Add birthplaces to DNA table

---

src/features/change_family_lists/change_family_lists.css
src/features/change_family_lists/change_family_lists.js

See this one: https://www.wikitree.com/g2g/1501022/spurious-reduplication-of-the-word-of-in-profile-bio-data.

Fix Change Family Lists 

---

src/features/edit_family_data/edit_family_data.js
src/features/make_radio_buttons_deselectable/make_radio_buttons_deselectable.js
src/manifest/manifest-chrome.json
src/manifest/manifest-firefox.json

This should have been included originally.

Add radio button de-selector to EditFamily page.

---

src/features/change_family_lists/change_family_lists.js
src/manifest/manifest-chrome.json
src/manifest/manifest-firefox.json

Fix this: https://discord.com/channels/494893309152722955/494893309152722957/1055263210757947473

Change family lists bug fixes

---

src/features/my_connections/my_connections.css
src/features/my_connections/my_connections.js

Fix a bug and add a Login button

Fix My Connections (again)

---

src/features/my_connections/my_connections.js
src/options.js

+ remove the top switch on the Options page

Fix a tiny mistake (missing '=')

---

package-lock.json
src/features/familyTimeline/familyTimeline.css
src/features/familyTimeline/familyTimeline.js
src/features/sort_theme_people/sort_theme_people.js

Combine the columns Relation, Name, Age, and Event into one, chaning the wording to be in the style "Death of sister, Louise, 22". Also change the date of events after death to "<ribbon symbol> + N"

Improve wording in Family Timeline

---

src/features/change_family_lists/change_family_lists.css
src/features/change_family_lists/change_family_lists.js
src/features/darkMode/darkMode.css

There were problems with some text not being visible in some coloured tables in Dark Mode.
In Change Family Lists, the parent status was not showing and some of the half-sibling colours were not showing.

Update dark mode and family lists

---

src/core/profileClasses.js

Other than whitespace changes and removing the unused function, this only changes line 2 and line 18 (now 10). The variables from the import were still needed to add the profile classes to the HTML elements (and had to be renamed).

fixed error from changes to pageType variables

---

src/core/profileClasses.js
src/features/accessibility/accessibility.css
src/features/accessibility/accessibility.js
src/features/accessibility/accessibility_options.js
src/features/readingMode/readingMode.js
src/features/readingMode/readingMode_options.js

This includes the updates from the development PR: https://github.com/wikitree/wikitree-browser-extension/pull/251

merged additional changes from development into OptionsUpdate

---

src/core/profileClasses.js
src/features/accessibility/accessibility.css
src/features/accessibility/accessibility.js
src/features/accessibility/accessibility_options.js
src/features/readingMode/readingMode.js
src/features/readingMode/readingMode_options.js

See [Schulz-482](https://www.wikitree.com/wiki/Schulz-482) for a good example. Separate PR to merge into OptionsUpdate.

added additional options to accessibility and reading mode

---

src/features/register_feature_options.js
src/features/scissors/scissors.js

Also corrects contributions by Smit-641

Scissors: change "Created by..." to "Creation of <profile-id> by..."

---

src/core/profileClasses.js
src/core/toggleCheckbox.css
src/features/readability/readability.css
src/features/readability/readability.js
src/features/register_feature_options.js

added CSS for dark mode to toggle button (used by reading mode/collapsible sources)
also formatted all other files that I touched with Prettier (formatting only; no code changes)

added dark mode styling to toggle button

---

src/content.js
src/features/confirm_thank_yous/confirm_thank_yous.js
src/features/register_feature_options.js

See here: https://www.wikitree.com/g2g/1566442/confirm-button-for-thank-yous

Confirm Thank Yous

---

src/features/language_setting/language_setting_options.js
src/features/readability/readability.css
src/features/register_feature_options.js
src/features/sourcepreview/sourcepreview.css
src/features/sourcepreview/sourcepreview.js
src/features/sourcepreview/sourcepreview_options.js
src/features/spacepreview/spacepreview.css
src/features/spacepreview/spacepreview.js
src/features/spacepreview/spacepreview_options.js
src/features/sticky_header/sticky_header.css

- created "options" scripts for 3 features
- additional option for source preview to remove the back-reference links
- renamed space preview to work with multiple pages and added options for both space pages and category pages

Tweaks to source and space previews
